module.exports={
    data:{
        name:"help",
        description:"TANAKAのhelpを表示します"
    },
    run:{
        tanaka(discord,data){
            discord.i.reply(data.map(command=>`commandname:${command.name},description:${command.description}`).join("/n"));
        }
    }
}